2011-03-22 09:51:57,109 [main] INFO  ME2 - me2.server.login.db.DBConnectionPool complete init.
2011-03-22 09:52:18,687 [main] INFO  ME2 - 昵称过滤列表加载完毕
2011-03-22 09:52:18,734 [main] INFO  ME2 - 账号统计已启动
2011-03-22 09:52:48,750 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.Statement$$EnhancerByProxool$$3cbe900c.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 09:59:26,906 [main] INFO  ME2 - me2.server.login.db.DBConnectionPool complete init.
2011-03-22 09:59:48,484 [main] INFO  ME2 - 昵称过滤列表加载完毕
2011-03-22 09:59:48,515 [main] INFO  ME2 - 账号统计已启动
2011-03-22 10:00:18,515 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 10:10:18,531 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 10:20:18,531 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 10:30:18,546 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 10:40:18,546 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 10:50:18,562 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 11:00:18,578 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 11:10:18,578 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 11:20:18,593 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 11:30:18,593 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 11:40:18,609 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 11:50:18,609 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 12:00:18,609 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 12:10:18,625 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 12:20:18,625 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 12:30:18,625 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$153fb37a.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 12:31:41,531 [main] INFO  ME2 - me2.server.login.db.DBConnectionPool complete init.
2011-03-22 12:32:03,218 [main] INFO  ME2 - 昵称过滤列表加载完毕
2011-03-22 12:32:03,265 [main] INFO  ME2 - 账号统计已启动
2011-03-22 12:32:33,281 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$d939bc7.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 12:42:33,265 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$d939bc7.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 12:52:33,265 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$d939bc7.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 13:02:33,265 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$d939bc7.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 13:12:33,281 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$d939bc7.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 13:22:33,296 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor45.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$d939bc7.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 13:23:53,062 [main] INFO  ME2 - me2.server.login.db.DBConnectionPool complete init.
2011-03-22 13:24:35,953 [main] INFO  ME2 - 昵称过滤列表加载完毕
2011-03-22 13:24:36,000 [main] INFO  ME2 - 账号统计已启动
2011-03-22 13:25:06,000 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.Wrapper$$EnhancerByProxool$$13cdc3ff.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 13:35:06,000 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.Wrapper$$EnhancerByProxool$$13cdc3ff.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 13:45:06,000 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.Wrapper$$EnhancerByProxool$$13cdc3ff.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 13:45:47,375 [main] INFO  ME2 - me2.server.login.db.DBConnectionPool complete init.
2011-03-22 13:46:30,281 [main] INFO  ME2 - 昵称过滤列表加载完毕
2011-03-22 13:46:30,328 [main] INFO  ME2 - 账号统计已启动
2011-03-22 13:46:35,031 [http-7000-Processor23] ERROR ME2 - 
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:327)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:97)
	at loginserver.LoginServlet.doGet(LoginServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:746)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:433)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:304)
	at org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:991)
	at org.apache.coyote.Response.action(Response.java:182)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:322)
	... 19 more
2011-03-22 13:47:00,328 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$f62293fc.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 13:57:00,343 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$f62293fc.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 14:07:00,343 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$f62293fc.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 14:15:24,828 [main] INFO  ME2 - me2.server.login.db.DBConnectionPool complete init.
2011-03-22 14:16:07,406 [main] INFO  ME2 - 昵称过滤列表加载完毕
2011-03-22 14:16:07,453 [main] INFO  ME2 - 账号统计已启动
2011-03-22 14:16:37,453 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 14:26:37,468 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 14:36:37,468 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 14:46:37,484 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 14:56:37,500 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 15:06:37,500 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 15:16:37,515 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 15:26:37,531 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 15:36:37,531 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 15:44:28,703 [http-7000-Processor23] ERROR ME2 - 
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:327)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:97)
	at loginserver.LoginServlet.doGet(LoginServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:746)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:433)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:304)
	at org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:991)
	at org.apache.coyote.Response.action(Response.java:182)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:322)
	... 19 more
2011-03-22 15:46:37,546 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 15:56:37,546 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 16:00:59,140 [http-7000-Processor25] ERROR ME2 - 
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:327)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:97)
	at loginserver.LoginServlet.doGet(LoginServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:746)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:433)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:304)
	at org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:991)
	at org.apache.coyote.Response.action(Response.java:182)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:322)
	... 19 more
2011-03-22 16:01:06,921 [http-7000-Processor24] ERROR ME2 - 
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:327)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:97)
	at loginserver.LoginServlet.doGet(LoginServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:746)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:433)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:304)
	at org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:991)
	at org.apache.coyote.Response.action(Response.java:182)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:322)
	... 19 more
2011-03-22 16:03:19,593 [http-7000-Processor25] ERROR ME2 - 
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:327)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:97)
	at loginserver.LoginServlet.doGet(LoginServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:746)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:433)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:304)
	at org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:991)
	at org.apache.coyote.Response.action(Response.java:182)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:322)
	... 19 more
2011-03-22 16:06:37,546 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 16:16:37,562 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 16:20:34,140 [http-7000-Processor20] ERROR ME2 - 
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:327)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:97)
	at loginserver.LoginServlet.doGet(LoginServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:746)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:433)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:304)
	at org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:991)
	at org.apache.coyote.Response.action(Response.java:182)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:322)
	... 19 more
2011-03-22 16:20:45,406 [http-7000-Processor23] ERROR ME2 - 
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:327)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:97)
	at loginserver.LoginServlet.doGet(LoginServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:746)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:433)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:304)
	at org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:991)
	at org.apache.coyote.Response.action(Response.java:182)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:322)
	... 19 more
2011-03-22 16:20:57,109 [http-7000-Processor22] ERROR ME2 - 
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:327)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:97)
	at loginserver.LoginServlet.doGet(LoginServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:746)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:433)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:304)
	at org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:991)
	at org.apache.coyote.Response.action(Response.java:182)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:322)
	... 19 more
2011-03-22 16:26:37,578 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 16:36:37,578 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 16:46:37,578 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 16:56:37,593 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 16:59:39,296 [http-7000-Processor24] ERROR ME2 - 
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:327)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:97)
	at loginserver.LoginServlet.doGet(LoginServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:746)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:433)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:304)
	at org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:991)
	at org.apache.coyote.Response.action(Response.java:182)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:322)
	... 19 more
2011-03-22 17:06:37,609 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 17:16:37,609 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 17:26:37,625 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 17:36:37,625 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 17:46:37,640 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 17:56:37,656 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 18:06:37,656 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 18:16:37,671 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 18:26:37,671 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 18:36:37,687 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 18:46:37,687 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 18:56:37,703 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 19:06:37,703 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 19:16:37,703 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 19:26:37,718 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 19:36:37,718 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 19:46:37,718 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 19:56:37,718 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 20:06:37,734 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 20:16:37,734 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 20:26:37,750 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 20:36:37,750 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 20:46:37,750 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 20:56:37,765 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 21:06:37,765 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 21:10:42,750 [http-7000-Processor19] ERROR ME2 - 
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:327)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:97)
	at loginserver.LoginServlet.doGet(LoginServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:746)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:433)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:304)
	at org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:991)
	at org.apache.coyote.Response.action(Response.java:182)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:322)
	... 19 more
2011-03-22 21:16:37,765 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 21:26:37,765 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 21:36:37,781 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 21:46:37,781 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 21:56:37,781 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 22:06:37,781 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 22:08:28,218 [http-7000-Processor20] ERROR ME2 - 
ClientAbortException:  java.net.SocketException: Connection reset by peer: socket write error
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:327)
	at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:293)
	at org.apache.catalina.connector.CoyoteOutputStream.flush(CoyoteOutputStream.java:97)
	at loginserver.LoginServlet.doGet(LoginServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:619)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:746)
	at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:433)
	at org.apache.coyote.http11.InternalOutputBuffer.flush(InternalOutputBuffer.java:304)
	at org.apache.coyote.http11.Http11Processor.action(Http11Processor.java:991)
	at org.apache.coyote.Response.action(Response.java:182)
	at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:322)
	... 19 more
2011-03-22 22:16:37,781 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 22:26:37,796 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 22:36:37,796 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 22:46:37,796 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 22:56:37,796 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 23:06:37,796 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 23:16:37,812 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 23:26:37,812 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 23:36:37,812 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 23:46:37,812 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-22 23:56:37,828 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
2011-03-23 00:06:37,828 [Timer-26] ERROR ME2 -  获取神州付充值信息 error: 
com.mysql.jdbc.exceptions.MySQLSyntaxErrorException: Table 'xj_account.szf_chargeup' doesn't exist
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1573)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1665)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3124)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1149)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1262)
	at sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.logicalcobwebs.proxool.ProxyStatement.invoke(ProxyStatement.java:100)
	at org.logicalcobwebs.proxool.ProxyStatement.intercept(ProxyStatement.java:57)
	at $java.sql.PreparedStatement$$EnhancerByProxool$$2aca52f0.executeQuery(<generated>)
	at me2.server.login.db.LoginDAO.getNotToServerSZFCharge(LoginDAO.java:1383)
	at me2.server.login.LoginService$ReSendSZFResultTask.run(LoginService.java:2048)
	at java.util.TimerThread.mainLoop(Timer.java:512)
	at java.util.TimerThread.run(Timer.java:462)
